/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package src;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.GraphicsEnvironment;
import java.io.File;
import java.io.IOException;
import java.nio.charset.Charset;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardOpenOption;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Alan
 */
public class UsingJFileChooser extends javax.swing.JFrame {

    /**
     * Creates new form SampleWP
     */
    public UsingJFileChooser() {
        initComponents();
        

        
        
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jta = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openJMenuItem = new javax.swing.JMenuItem();
        saveJMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutJMenuItem = new javax.swing.JMenuItem();
        copyJMenuItem = new javax.swing.JMenuItem();
        pasteJMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        selectAllJMenuItem = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Word Processor");

        jta.setColumns(20);
        jta.setRows(5);
        jScrollPane2.setViewportView(jta);

        getContentPane().add(jScrollPane2, java.awt.BorderLayout.CENTER);

        fileMenu.setText("File");

        openJMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        openJMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/open.gif"))); // NOI18N
        openJMenuItem.setText("Open");
        openJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openJMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(openJMenuItem);

        saveJMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        saveJMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/save.gif"))); // NOI18N
        saveJMenuItem.setText("Save");
        saveJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveJMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(saveJMenuItem);

        jMenuBar1.add(fileMenu);

        editMenu.setText("Edit");

        cutJMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        cutJMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cut.gif"))); // NOI18N
        cutJMenuItem.setText("Cut");
        cutJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cutJMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(cutJMenuItem);

        copyJMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        copyJMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/copy.gif"))); // NOI18N
        copyJMenuItem.setText("Copy");
        copyJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyJMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(copyJMenuItem);

        pasteJMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        pasteJMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/paste.gif"))); // NOI18N
        pasteJMenuItem.setText("Paste");
        pasteJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasteJMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(pasteJMenuItem);
        editMenu.add(jSeparator1);

        selectAllJMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        selectAllJMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/selectall.gif"))); // NOI18N
        selectAllJMenuItem.setText("Select All");
        selectAllJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectAllJMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(selectAllJMenuItem);

        jMenu3.setText("Colour");

        jMenuItem1.setText("Background Colour");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem2.setText("Text Colour");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        editMenu.add(jMenu3);

        jMenuBar1.add(editMenu);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(816, 638));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void saveJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveJMenuItemActionPerformed
        
            JFileChooser jfc = new JFileChooser();

            int option = jfc.showSaveDialog(this);

            if (option == JFileChooser.APPROVE_OPTION) {
                File f = jfc.getSelectedFile();
                Path pathToFile = Paths.get(f.getPath());
            
             String linesotoadd = jta.getText();
             try {
                Files.write(pathToFile, linesotoadd.getBytes(), StandardOpenOption.CREATE);
               
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "Opps!! Something has gone wrong,\n" + ex.toString());
            }
         }
         
         
    }//GEN-LAST:event_saveJMenuItemActionPerformed

    private void openJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openJMenuItemActionPerformed
        
        JFileChooser jfc = new JFileChooser();
        
        int choice = jfc.showDialog(this, "Select File");

        if (choice == JFileChooser.APPROVE_OPTION) {
        
            String output = "";
            
            List<String> lines = null;
            
            File f = jfc.getSelectedFile();
            
            Path source = Paths.get(f.getAbsolutePath());
            
            try {
                lines = Files.readAllLines(source,Charset.forName("UTF-8"));
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "Opps!! Something has gone wrong,\n" + ex.toString());
            }
            
            for(String item : lines ){
                 output += item + "\n";
            }
            
            jta.setText(output);
            
        }
            
            
    }//GEN-LAST:event_openJMenuItemActionPerformed

    private void pasteJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasteJMenuItemActionPerformed
        jta.paste();
    }//GEN-LAST:event_pasteJMenuItemActionPerformed

    private void cutJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cutJMenuItemActionPerformed
        jta.cut();
    }//GEN-LAST:event_cutJMenuItemActionPerformed
    private void copyJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyJMenuItemActionPerformed
        jta.copy();
    }//GEN-LAST:event_copyJMenuItemActionPerformed

    private void selectAllJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectAllJMenuItemActionPerformed
        jta.selectAll();
    }//GEN-LAST:event_selectAllJMenuItemActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Color color =  JColorChooser.showDialog(this, "Select A Text Colour", Color.BLACK);
        
        jta.setForeground(color);
    
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Color color =  JColorChooser.showDialog(this, "Select A Background Colour", Color.WHITE);
        
        jta.setBackground(color);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsingJFileChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsingJFileChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsingJFileChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsingJFileChooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new UsingJFileChooser().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem copyJMenuItem;
    private javax.swing.JMenuItem cutJMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextArea jta;
    private javax.swing.JMenuItem openJMenuItem;
    private javax.swing.JMenuItem pasteJMenuItem;
    private javax.swing.JMenuItem saveJMenuItem;
    private javax.swing.JMenuItem selectAllJMenuItem;
    // End of variables declaration//GEN-END:variables
}
